weekdays = ("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
print(weekdays)
print(type(weekdays))
print(len(weekdays))
print(weekdays[2])
print(weekdays[-1])
fruits = (["apples", "bananas", "cherries"], ["oranges", "clementines", "mandarins"])
temp = fruits[0].pop()
fruits[1].append(temp)
print(fruits)